# Walkie-Talkie Config File

# Channel settings
max-canal=256

# Speaker setting
speaker-distance=10000
voice-duplication=true

# Walkie-Talkie settings
wooden-walkie-talkie-range=100
stone-walkie-talkie-range=200
iron-walkie-talkie-range=300
golden-walkie-talkie-range=400
diamond-walkie-talkie-range=700
netherite-walkie-talkie-range=10000000

# Cross dimensions settings
cross-dimensions-enabled=false
apply-dimension-scale=true
